name: Student Grade Checker CD Pipeline

on:
  push:
    branch:
      - main 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write    # Required if using OIDC (e.g., AWS, GCP, Azure OpenID Connect)

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: Setup Github Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'
      
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v5



    




