name: Student Garde Checker CI pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: # Enables manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Fetch the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name : List project files
        run : ls

      - name : show the current directoty
        run : pwd
            
      - name : Install dependencies
        run : npm install

      - name : Run Tests
        run: npm test
  display-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display Project Information
        run: |
          echo "========================================="
          echo "PROJECT INFORMATION"
          echo "========================================="
          echo "Repository Name:  ${{ github.repository }}"
          echo "Workflow Name:    ${{ github.workflow }}"
          echo "Triggered By:     ${{ github.actor }}"
          echo "Current Branch:   ${{ github.ref_name }}"
          echo "Commit SHA:       ${{ github.sha }}"
          echo "Runner OS:        ${{ runner.os }}"
          echo "========================================="
      

